#version: '3.3'
#services:
#  frontend:
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
#    volumes:
#      - ../frontend/:/app/result_build/
#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
#      - ../docs/:/usr/share/nginx/html/api/docs/
#  db:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: foodgram
#      POSTGRES_USER: foodgram_user
#      POSTGRES_PASSWORD: foodgram_password
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

#
#version: '3.3'
#services:
#
#  frontend:
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
#    volumes:
#      - ../frontend/:/app/result_build/
#    depends_on:
#      - backend
#
#  db:
#    image: postgres:latest
#    volumes:
#      - postgres-db-data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: foodgram
#      POSTGRES_USER: foodgram_user
#      POSTGRES_PASSWORD: foodgram_password
#    ports:
#      - "5432:5432"
#
#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
#      - ../docs/:/usr/share/nginx/html/api/docs/
#      - static_value:/usr/share/nginx/html/static/
#      - media_value:/usr/share/nginx/html/media/
#    depends_on:
#      - frontend
#
#  backend:
#    build:
#      context: ../backend
#      dockerfile: Dockerfile
#    restart: always
#    volumes:
#      - static_value:/app/static/
#      - media_value:/app/media/recipes
#    depends_on:
#      - db
#    environment:
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_NAME: foodgram
#      DB_USER: foodgram_user
#      DB_PASSWORD: foodgram_password
#
#volumes:
#  postgres-db-data:
#  static_value:
#  media_value:

version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres-db-data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app_back/static/
      - media_value:/app_back/media/
      - docs:/app/api_back/docs/
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres-db-data:
  static_value:
  media_value:
  docs:
