# Generated by Django 2.2.19 on 2023-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230617_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(default='еуtest'),
            preserve_default=False,
        ),
    ]
