# Generated by Django 3.2.19 on 2023-06-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230628_0311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
